@HotelListing.API_HostAddress = https://localhost:7162


@id=3



GET {{HotelListing.API_HostAddress}}/api/hotels

###

POST {{HotelListing.API_HostAddress}}/api/hotels
Content-Type: application/json

{
  "name": "Grand Plaza",
  "address": "123 Main St",
  "rating": 4.5
}

###

DELETE {{HotelListing.API_HostAddress}}/api/hotels/{{id}}

###

GET {{HotelListing.API_HostAddress}}/api/hotels/{{id}}

###

PUT {{HotelListing.API_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  "id": 3,
  "name": "Test Hotel",
  "address": "123 Main St",
  "rating": 4.5
}

###

GET {{HotelListing.API_HostAddress}}/api/countries

###

POST {{HotelListing.API_HostAddress}}/api/countries
Content-Type: application/json

{
  "Name": "Africa",
  "ShortName": "SA"
}

###

DELETE {{HotelListing.API_HostAddress}}/api/countries/{{id}}

###

GET {{HotelListing.API_HostAddress}}/api/countries/{{id}}

###

PUT {{HotelListing.API_HostAddress}}/api/countries/{{id}}
Content-Type: application/json

{
  "CountryId": 56,
  "Name": "United States of America",
  "ShortName": "US"
}

###

GET {{HotelListing.API_HostAddress}}/api/hotels

###

POST {{HotelListing.API_HostAddress}}/api/hotels
Content-Type: application/json

{
  "Name": "Last Hotel",
  "Address": "123 Main St",
  "Rating": 4.5,
  "CountryId": 3
}

###
DELETE {{HotelListing.API_HostAddress}}/api/hotels/{{id}}

###

GET {{HotelListing.API_HostAddress}}/api/hotels/{{id}}

###

PUT {{HotelListing.API_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  "Id": 2,
  "Name": "Hilton",
  "Address": "321 Main St",
  "Rating": 4.5,
  "CountryId": 1
}

###
